experiment_name: coco_regnet600m_fpn

system:
  gpus: [0, 1]
  num_workers: 12

dataset:
  name: coco
  train_txt_file: /datasets/COCO/trainvalno5k.txt
  eval_txt_file: /datasets/COCO/trainvalno5k.txt
  classes: ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck',
    'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat',
    'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
    'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
    'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle',
    'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
    'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake',
    'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop',
    'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink',
    'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']

model:
  cfg_path: model/cfg/regnetx-600m-fpn-coco.cfg
  # anchors: [[9, 13], [25, 17], [16, 31], [47, 29], [32, 51], [83, 48], [61, 91], [131, 99], [210, 189]]
  anchors_iou_threshold: 0.3

train:
  # scheduler: 'step'
  max_epochs: 60
  batch_size: 32
  # input_sizes: [480, 512, 544, 576]
  learning_rate_init: 4e-4
  # weight_decay: 2e-3

weight:
  backbone: weights/pretrained/regnetx_600m.pt
  # resume: weights/coco_regnet600m_fpn/model-25.pt

augment:
  # mixup_p: 0.38
  # color_p: 0.25
  # hflip_p: 0.5
  # crop_p: 0.65
  color_p: 0.

eval:
  after: 40
  batch_size: 80
  # partial: 10000
  iou_threshold: 0.65

prune:
  weight: weights/VOC_prune/model-0.pt
  new_cfg: model/cfg/myolo-prune.cfg

# sparse:
#   switch: on
