experiment_name: VOC_std_qat_test

system:
  gpus: [0, 1]
  num_workers: 6

dataset:
  train_txt_file: /home/eleflea/ramdata/Pascal_voc/train.txt
  eval_txt_file: /home/eleflea/ramdata/Pascal_voc/2007_test.txt

model:
  cfg_path: model/cfg/mobilenetv2-yolo.cfg
  # cfg_path: model/cfg/myolo-prune-40.cfg

train:
  batch_size: 12
  learning_rate_init: 2e-4
  max_epochs: 80

weight:
  resume: weights/VOC_std/model-70-0.7675.pt
  clear_history: on
  # backbone: weights/pretrained/mobilev2-prune40.pt

augment:
  # mixup_p: 0
  color_p: 0.

eval:
  after: 2
  batch_size: 16
  partial: 100

quant:
  switch: on
  disable_observer_after: 2
  freeze_bn_after: 4