experiment_name: VOC_std_ioufls

system:
  gpus: [0, 1]
  num_workers: 6

dataset:
  train_txt_file: /home/eleflea/ramdata/Pascal_voc/train.txt
  eval_txt_file: /home/eleflea/ramdata/Pascal_voc/2007_test.txt

model:
  cfg_path: model/cfg/mobilenetv2-yolo.cfg

train:
  # scheduler: 'step'
  max_epochs: 60
  batch_size: 32
  # input_sizes: [480, 512, 544, 576]
  learning_rate_init: 2e-4

# weight:
#   resume: weights/VOC_std_step60/model-29.pt

augment:
  # mixup_p: 0
  color_p: 0

eval:
  after: 40
  batch_size: 80

prune:
  weight: weights/VOC_prune/model-0.pt
  new_cfg: model/cfg/myolo-prune.cfg

# sparse:
#   on: on
