experiment_name: VOC_quant3

system:
  gpus: [0]
  num_workers: 6

dataset:
  train_txt_file: /home/eleflea/ramdata/Pascal_voc/train.txt
  eval_txt_file: /home/eleflea/ramdata/Pascal_voc/2007_test.txt

model:
  cfg_path: model/cfg/mobilenetv2-yolo.cfg

train:
  batch_size: 6
  learning_rate_init: 2e-4
  max_epochs: 80

# weight:
#   resume: weights/VOC_prune/model-6-0.5812.pt

augment:
  # mixup_p: 0
  color_p: 0

eval:
  after: 50
  batch_size: 12
  partial: 0

quant:
  switch: on
  disable_observer_after: 10
  freeze_bn_after: 8